### ISSUE TITLE
nova release

### ISSUE THREAD

**Issue by marcoT89** [connecta-solutions/angular-amchart#3]
Abri dois PR para vocês que já foram aceitos mas ainda não foi gerada uma nova release. Tem como gerar uma nova release ou vocês vão fazer novas alterações para gerar uma? Como está o andamento?

**Comment by marcoT89** [comment]
Vlw! Foi rápido hein!? hehe :+1:

**Comment by natanielpaiva** [comment]
Obrigado @marcoT89  pela contribuição!

**Comment by marcoT89** [comment]
Por nada @natanielpaiva ! Obrigado você pelo projeto open source.

Ah! Se você precisar de um programa para gerenciar várias versões do nodejs com linux sem ser por .rpm ou .deb dê uma olhada no meu repositório chamado 'nodem'. Bem simples e a vantagem em relação ao nvm é que ele instala no diretório do usuário, não precisando de privilégios sudo para instalar qualquer pacote. Vlw

**Comment by natanielpaiva** [comment]
Muito legal! Pode deixar, vou olhar sim!
Abraços
